name: '21 - Froala - Content Right Block Title, Description & CTA With Background'
multiple: FALSE
category: 'Call to action'
enabled: TRUE
fields:
  image:
    type: image
    label: 'Background'
  title:
    type: text
    label: 'Titre'
  description:
    type: textarea
    label: 'Description'
  link:
    type: url_extended
    label: 'Lien'
  link_alt:
    type: text
    label: 'Titre Lien'
  link_target:
    type: checkbox
    label: 'Ouvrir dans une nouvelle fenêtre'
  mode:
    type: checkbox
    label: 'Activer le mode inversé'
