name: '9 - Froala - Content Images 4 Cols'
multiple: TRUE
category: 'Froala'
enabled: TRUE
limit: 4
fields:
  image:
    type: image
    label: 'Thumbnail'
  image_alt:
    type: text
    label: 'Text alternatif'
extra_fields:
  title:
    type: text
    label: 'Titre'

