name: 'C44 - Testimonials image,name,description & role'
multiple: TRUE
category: 'Testimonials'
enabled: TRUE
fields:
  description:
    type: textarea
    label: 'Description'   
  name:
    type: text
    label: 'Name'
    options:
      '#required': TRUE
  role:
    type: text
    label: 'Role'
  image:
    type: image
    label: 'Image Profile'
    options:
      '#required': TRUE
  image_alt:
      type: text
      label: 'Text alternatif'
extra_fields:
  intro:
    type: textarea
    label: 'Introduction'      