name: '45 - Froala - Testimonials 3 Cols Image, Name, Role & Description With Background'
multiple: TRUE
category: 'Testimonials'
enabled: TRUE
fields:
  image:
    type: image
    label: 'Image Profile'
    options:
      '#required': TRUE
  image_alt:
      type: text
      label: 'Text alternatif'
  name:
    type: text
    label: 'Name'
    options:
      '#required': TRUE
  role:
    type: text
    label: 'Role'
  description:
    type: text_format
    label: 'Description'
    options:
      '#format': 'full_html'
      '#required': TRUE
extra_fields:
  intro:
    type: textarea
    lable: 'Introduction'
  mode:
    type: checkbox
    label: 'Active reverse mode' 