name: '70 - Froala - CTA Block Left Image, Title & Description With Image Right'
multiple: FALSE
category: 'Call to action'
enabled: TRUE
fields:
  image_1:
    type: image
    label: 'Image 1'
  image_alt_1:
     type: text
     label: 'Text alternatif'
  title:
    type: text
    label: 'Titre'
  description:
    type: text_format
    label: 'Description'
    options:
      '#format': 'full_html'
  link:
    type: url_extended
    label: 'Lien'
  link_alt:
    type: text
    label: 'Titre lien'
  link_target:
    type: checkbox
    label: 'Ouvrir dans une nouvelle fenêtre'
  image_2:
    type: image
    label: 'Image 2'
  image_alt_2:
      type: text
      label: 'Text alternatif'
  mode:
    type: checkbox
    label: 'Activer le mode inversé '
