name: '12 - Froala - Content Title, Description, CTA To Right & Image Left'
multiple: FALSE
category: 'Call to action'
enabled: TRUE
fields:
  title:
    type: text
    label: 'Titre'
  description:
    type: textarea
    label: 'Description'
  link:
    type: url_extended
    label: 'Lien'
  link_alt:
    type: text
    label: 'Titre Lien'
  link_target:
    type: checkbox
    label: 'Ouvrir dans une nouvelle fenêtre'
  image:
    type: image
    label: 'Background'
    options:
      '#required': TRUE
  image_alt:
    type: text
    label: 'Text alternatif'
