name: '61 - Froala - CTA Inline Right Title'
multiple: FALSE
category: 'Call to action'
enabled: TRUE
fields:
  title:
    type: text
    label: 'Titre'
    options:
      '#required': TRUE
  link:
    type: url_extended
    label: 'Lien'
    options:
      '#required': TRUE
  link_alt:
    type: text
    label: 'Titre lien'
    options:
      '#required': TRUE
  link_target:
    type: checkbox
    label: 'Ouvrir dans une nouvelle fenêtre'
  mode:
    type: checkbox
    label: 'Activer le mode inversé '
