name: "40 - Froala - Testimonials Listing 11 Company's"
multiple: TRUE
category: 'Content'
enabled: TRUE
limit: 11
fields:
  logo:
    type: image
    label: 'Logo company'
    options:
      '#required': TRUE
  image_alt:
      type: text
      label: 'Text alternatif'
extra_fields:
  title:
      type: text
      label: 'Titre'
