<?php

/**
 * @file
 * Primary module hooks for vactory_register module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

function vactory_register_theme($existing, $type, $theme, $path) {
  return [
    'vactory_register_form' => [
      'template' => 'register',
      'variables' => [
        'form_register' => NULL,
        'extension' => NULL
      ],
    ],
  ];
}

function vactory_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  
  
  if($form_id === 'user_register_form'){
    
    $form['account']['mail']['#default_value'] = 'abc@xyz.com';
    $form['account']['pass']['#required'] = FALSE;
    $form['account']['mail']['#required'] = FALSE;

    array_unshift($form['actions']['submit']['#submit'], 'vactory_register'); 
  }
}



function vactory_register(&$form, \Drupal\Core\Form\FormStateInterface $form_state){
  $form_state->setValue('mail', $form_state->getValue('field_telephone')[0]['value'].'@tpe.com');
}


