name: '69 - Froala - CTA Image, Title & Description With Background'
multiple: FALSE
category: 'Call to action'
enabled: TRUE
fields:
  image_1:
    type: image
    label: 'Image'
  image_alt:
    type: text
    label: 'Text alternatif'
  title:
    type: text
    label: 'Titre'
  description:
    type: textarea
    label: 'Description'
  link:
    type: url_extended
    label: 'Lien'
  link_alt:
    type: text
    label: 'Titre lien'
  link_target:
    type: checkbox
    label: 'Ouvrir dans une nouvelle fenêtre'
