name: '37 - Froala - Team 4 Block Picto Inline Name, Role & Description'
multiple: TRUE
category: 'Teams'
enabled: TRUE
limit: 4
fields:
  image:
    type: image
    label: 'Image Profile'
    options:
      '#required': TRUE
  image_alt:
      type: text
      label: 'Text alternatif'
  name:
    type: text
    label: 'Name'
    options:
      '#required': TRUE
  role:
    type: text
    label: 'Role'
  description:
    type: textarea
    label: 'Description'
extra_fields:
  title:
    type: text
    label: 'Titre'
  description:
    type: textarea
    label: 'Description'
