<?php

/**
 * @file
 * Contain related hooks.
 */

use Drupal\core\Site\Settings;

/**
 * Implements HOOK_ckeditor_css_alter().
 */
function vactory_ckeditor_ckeditor_css_alter(&$css, $editor) {
  $ckeditor_stylesheet_url = Settings::get('CKEDITOR_STYLESHEET_URL', NULL);
  if ( $ckeditor_stylesheet_url ) {
    $css[] = $ckeditor_stylesheet_url;
  }
}

/**
 * Implements HOOK_ckeditor_plugin_info_alter().
 */
function vactory_ckeditor_ckeditor_plugin_info_alter(array &$plugins) {
  $plugins['internal']['class'] = 'Drupal\vactory_ckeditor\Plugins\CKEditorPlugin\CustomInternal';
}
