name: 'C42 - Testimonials slider'
multiple: TRUE
category: 'Testimonials'
enabled: TRUE
fields:
  description:
    type: text_format
    label: 'Description'
    options:
      '#format': 'full_html'
  name:
    type: text
    label: 'Name'
    options:
      '#required': TRUE
  role:
    type: text
    label: 'Role'
  image:
    type: image
    label: 'Image Profile'
    options:
      '#required': TRUE
  image_alt:
      type: text
      label: 'Text alternatif'
extra_fields:
  intro:
    type: textarea
    label: 'Introduction'