name: 'C08 - Vidéo Youtube'
multiple: FALSE
category: 'Videos'
enabled: TRUE
fields:
  image:
    type: image
    label: 'Image'
    options:
      '#required': TRUE
  image_alt:
    type: text
    label: 'Image alt'
  video:
    type: text
    label: 'Video link'
    options:
      '#required': TRUE
      '#description': '<b><i class="link">How ?</i></b><br><b>URL Example</b>: https://www.youtube.com/watch?v=BZDyr2OpWBU <br> <b>Value to insert</b>: BZDyr2OpWBU'
  description:
    type: text_format
    label: 'Description'
    options:
      '#format': 'full_html'
