name: '10 - Froala - Content Text & Image Right'
multiple: FALSE
category: 'Froala'
enabled: TRUE
fields:
  title:
    type: text
    label: 'Titre'
  description:
    type: text_format
    label: 'Description'
    options:
      '#format': 'full_html'
  image:
    type: image
    label: 'Image'
    options:
      '#required': TRUE
  image_alt:
      type: text
      label: 'Text alternatif'
