name: 'C41 - Widget Links'
category: 'Content'
multiple: TRUE
enabled: TRUE
fields:
  image:
    type: image
    label: 'Icon'
  image_alt:
    type: text
    label: 'Image alt'
  description:
    type: textarea
    label: 'Description'
  link:
    type: url_extended
    label: 'Lien'
  link_target:
    type: checkbox
    label: 'Ouvrir dans une nouvelle fenêtre'  
