name: '42 - Froala - Testimonials 2 Cols Image, Description, Name & Role'
multiple: TRUE
category: 'Testimonials'
enabled: TRUE
fields:
  image:
    type: image
    label: 'Image Profile'
    options:
      '#required': TRUE
  image_alt:
      type: text
      label: 'Text alternatif'
  description:
    type: textarea
    label: 'Description'
  name:
    type: text
    label: 'Name'
    options:
       '#required': TRUE
  role:
    type: text
    label: 'Role'
extra_fields:
  intro:
    type: textarea
    lable: 'Introduction'
  reverse_mode:
    type: checkbox
    label: 'Active mode invers' 
  mode_top:
    type: checkbox
    label: 'Image Top' 