name: '32 - Froala - Team 7 Block Picto, Name & Role'
multiple: TRUE
category: 'Teams'
enabled: TRUE
limit: 7
fields:
  image:
    type: image
    label: 'Image Profile'
    options:
      '#required': TRUE
  image_alt:
      type: text
      label: 'Text alternatif'
  name:
    type: text
    label: 'Name'
    options:
      '#required': TRUE
  role:
    type: text
    label: 'Role'
extra_fields:
  title:
      type: text
      label: 'Titre'
