name: '57 - Froala - CTA Title & Description'
multiple: FALSE
category: 'Call to action'
enabled: TRUE
fields:
  title:
    type: text
    label: 'Titre'
  description:
    type: text_format
    label: 'Description'
    options:
      '#format': 'full_html'
  link:
    type: url_extended
    label: 'Lien'
  link_alt:
    type: text
    label: 'Titre lien'
  link_target:
    type: checkbox
    label: 'Ouvrir dans une nouvelle fenêtre'
