name: '46 - Froala - Testimonials 3 Cols Description, Image, Name & Role'
multiple: TRUE
category: 'Testimonials'
enabled: TRUE
fields:
  description:
    type: textarea
    label: 'Description'
    options:
      '#required': TRUE
  image:
    type: image
    label: 'Image Profile'
    options:
      '#required': TRUE
  image_alt:
      type: text
      label: 'Text alternatif'
  name:
    type: text
    label: 'Name'
    options:
      '#required': TRUE
  role:
    type: text
    label: 'Role'
extra_fields:
  intro:
    type: textarea
    label: 'Introduction'
  mode:
    type: checkbox
    label: 'Active reverse mode' 