name: '34 - Froala - Team 8 Block Picto, Name & Description'
multiple: TRUE
category: 'Teams'
enabled: TRUE
limit: 8
fields:
  image:
    type: image
    label: 'Image Profile'
    options:
      '#required': TRUE
  image_alt:
      type: text
      label: 'Text alternatif'
  name:
    type: text
    label: 'Name'
    options:
      '#required': TRUE
  description:
    type: textarea
    label: 'Description'
extra_fields:
  title:
      type: text
      label: 'Titre'
