name: '91 - Froala - Features 2 Blocks Thumbnail With Title & Description'
multiple: TRUE
category: 'Froala'
enabled: TRUE
limit: 2
fields:
  image:
    type: image
    label: 'Image'
  image_alt:
    type: text
    label: 'Text alternatif'
  title:
    type: text
    label: 'Titre'
  description:
    type: textarea
    label: 'Description'
