name: 'U06 - UniteGallery - Nested'
multiple: TRUE
category: 'UniteGallery'
enabled: TRUE
fields:
  title:
    type: text
    label: 'Title'
    options:
      '#required': TRUE
  thumbnail:
    type: image
    label: 'Thumbnail'
    options:
      '#required': TRUE
      '#description': 'Image size largeur: 400px'
  image:
    type: image
    label: 'Image'
    options:
      '#required': TRUE
