name: 'S07 - Slider swiper full background'
multiple: TRUE
category: 'Sliders'
enabled: TRUE
fields:
  image:
    type: image
    label: 'Image'
    options:
      '#required': TRUE
  title:
    type: text
    label: 'Titre'
    options:
      '#required': TRUE
  description:
    type: textarea
    label: 'Description'
    options:
      '#required': TRUE
