name: '73 - Froala - CTA Title, Description & 2 CTA With Background'
multiple: FALSE
category: 'Call to action'
enabled: TRUE
fields:
  title:
    type: text
    label: 'Titre'
  description:
    type: textarea
    label: 'Description'
  link_1:
    type: url_extended
    label: 'Lien 1'
  link_alt_1:
    type: text
    label: 'Titre lien 1'
  link_target_1:
    type: checkbox
    label: 'Ouvrir dans une nouvelle fenêtre'
  link_2:
    type: url_extended
    label: 'Lien 2'
  link_alt_2:
    type: text
    label: 'Titre lien 2'
  link_target_2:
    type: checkbox
    label: 'Ouvrir dans une nouvelle fenêtre'
