<?php

/**
 * @file
 * Contain related hooks.
 */

use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\StreamWrapper\StreamWrapperManager;
use Drupal\Core\Url;
use Drupal\media\Entity\Media;
use Drupal\views\Views;

/**
 * Implements hook_df_jsonapi_output_alter().
 */
function vactory_government_member_df_jsonapi_output_alter(&$content)
{

  $display_id = "block_slider";

  if ($content['template'] === 'vactory_gouvernance:tabs') {
    $display_id = "block_tabs";
  }

  if (
    $content['template'] === 'vactory_gouvernance:slider' ||
    $content['template'] === 'vactory_gouvernance:tabs'
  ) {
    $name = "vactory_gouvernance";

    $image_app_base_url = Url::fromUserInput('/app-image/')
      ->setAbsolute()->toString();
    $lqipImageStyle = \Drupal\image\Entity\ImageStyle::load('lqip');
    $thumbnailImageStyle = \Drupal\image\Entity\ImageStyle::load('gouvernance_thumbnail');

    $view = Views::getView($name);
    if (!$view || !$view->access($display_id)) {
      $content['data'] = [];
      return;
    }

    $view->setDisplay($display_id);
    $view->preExecute();
    $view->execute();
    $result = $view->result;

    $nodes = [];
    foreach ($result as $row) {
      $node = $row->_entity;
      $mid1 = $node->get('field_vactory_media_image')
        ->getValue()[0]['target_id'];
      $file1 = Media::load($mid1);
      $file1_uri = $file1->thumbnail->entity->getFileUri();
      $theme = $node->get('field_vactory_taxonomy_1')->entity->label();
      $theme_id = $node->get('field_vactory_taxonomy_1')->entity->id();

      $imgCover = [];
      $imgCover['_default'] = file_create_url($file1_uri);
      $imgCover['_lqip'] = $lqipImageStyle->buildUrl($file1_uri);
      $imgCover['_thumbnail'] = $thumbnailImageStyle->buildUrl($file1_uri);
      $imgCover['uri'] = StreamWrapperManager::getTarget($file1_uri);
      $imgCover['fid'] = $file1->thumbnail->entity->fid->value;
      $imgCover['file_name'] = $file1->label();
      $imgCover['base_url'] = $image_app_base_url;

      array_push($nodes, [
        "key" => $node->uuid(),
        "title" => $node->label(),
        "image" => $imgCover,
        "role" => $theme,
        "role_id" => $theme_id,
        "role_title" => $node->get('field_vactory_name')->getValue(),
      ]);
    }

    $content['data'] = $nodes;
  }

  if ($content['template'] === 'vactory_gouvernance:tabs') {
    $vid = 'vactory_governance_role';
    $raw_terms = \Drupal::service('entity.manager')
      ->getStorage('taxonomy_term')
      ->loadTree($vid);

    $terms = [];
    foreach ($raw_terms as $term) {
      array_push($terms, [
        'id' => $term->tid,
        'name' => $term->name,
      ]);
    }

    $content['terms'] = $terms;
  }

}
