name: '74 - Froala - Features 6 Blocks Title & Description'
multiple: TRUE
category: 'Froala'
enabled: TRUE
limit: 6
fields:
  title:
    type: text
    label: 'Titre'
    options:
      '#required': TRUE
  description:
    type: textarea
    label: 'Description'
    options:
      '#required': TRUE
