<?php

/**
 * @file
 * Module related hooks.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function vactory_quiz_theme($existing, $type, $theme, $path) {
  return [
    'vactory_quiz_answer_summary' => [
      'template' => 'vactory-quiz-answer-summary',
      'variables' => [
        'content' => NULL,
      ],
    ],
    'vactory_quiz__quiz_question' => [
      'template' => 'quiz-question',
      'variables' => [
        'question' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_multiple_field_remove_button_field_types_alter().
 */
function vactory_quiz_multiple_field_remove_button_field_types_alter(array &$fieldTypes) {
  $fieldTypes[] = "vactory_quiz_question";
}

/**
 * Implements hook_field_widget_form_alter().
 */
function vactory_quiz_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  if ($context['widget']->getPluginId() === 'vactory_quiz_question_widget') {
    $element['#title'] = t('Question @num', ['@num' => $element['#delta'] + 1]);
  }
}
