name: '54 - Froala - Pricing Light Image, Title, Price, Items & CTA'
multiple: TRUE
category: 'Tables'
enabled: TRUE
limit: 3
fields:
  image:
    type: image
    label: 'Image'
  image_alt:
      type: text
      label: 'Text alternatif'
  title:
    type: text
    label: 'Titre'
  price:
    type: text
    label: 'Price'
  lists:
    type: text_format
    label: 'Items'
    options:
      '#format': 'full_html'
  link:
    type: url_extended
    label: 'Lien'
  link_alt:
    type: text
    label: 'Titre lien'
  link_target:
    type: checkbox
    label: 'Ouvrir dans une nouvelle fenêtre'
extra_fields:
  title:
      type: text
      label: 'Titre'
