<?php

/**
 * @file
 * Primary module hooks for vactory_jsonapi module.
 */

use Drupal\Core\Entity\ContentEntityFormInterface;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Site\Settings;
use Drupal\Core\Url;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_form_alter().
 */
function vactory_jsonapi_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  $form_object = $form_state->getFormObject();
  if (!($form_object instanceof ContentEntityFormInterface)) {
    return;
  }
  $entity = $form_object->getEntity();
  $op = $form_object->getOperation();

  if (!($entity instanceof ContentEntityInterface)) {
    return;
  }

  if (in_array($op, ['edit', 'add', 'default'], TRUE)) {
    unset($form['actions']['preview']);
  }

  $frontend_url = Settings::get('FRONTEND_URL', FALSE);
  if (!$frontend_url || empty($frontend_url)) {
    return;
  }

  if ($op === 'edit') {
    $form_langcode = $form_object->getFormLangcode($form_state);
    $form['actions']['front_preview'] = [
      '#type' => 'link',
      '#title' => t('Preview'),
      '#weight' => 20,
      '#url' => Url::fromUri($frontend_url, [
        'query' => [
          '_lng' => $form_langcode,
          'nid' => $entity->id(),
          'content_type' => $entity->bundle()
        ]
      ]),
      '#attributes' => [
        'id' => 'frontend-preview-button',
        'class' => ['action-link', 'action-link', 'action-link--icon-show'],
        'target' => '_blank'
      ],
    ];
    $form['#attached']['library'][] = 'vactory_jsonapi/preview_button';
  }

}

/**
 * Implements hook_entity_base_field_info().
 */
function vactory_jsonapi_entity_base_field_info(EntityTypeInterface $entity_type) {
  $base_table = $entity_type->getBaseTable();
  $canonical_template_exists = $entity_type->hasLinkTemplate('canonical');
  $fields = [];

  if (!empty($base_table) && $canonical_template_exists) {
    $fields['internal_user'] = BaseFieldDefinition::create('map')
      ->setLabel(t('Internal User'))
      ->setDescription(t('User profile'))
      ->setTranslatable(FALSE)
      ->setClass('\Drupal\vactory_jsonapi\Plugin\Field\InternalUserEntityFieldItemList')
      ->setComputed(TRUE)
      ->setReadOnly(TRUE)
      ->setTargetEntityTypeId($entity_type->id())
      ->setDisplayConfigurable('form', FALSE)
      ->setDisplayConfigurable('view', FALSE);
  }

  if ($entity_type->id() === 'comment') {
    $fields['extra_data'] = BaseFieldDefinition::create('map')
      ->setLabel(t('Comment Extra Data'))
      ->setDescription(t('Comment Extra Data'))
      ->setTranslatable(FALSE)
      ->setClass('\Drupal\vactory_jsonapi\Plugin\Field\InternalCommentEntityFieldItemList')
      ->setComputed(TRUE)
      ->setReadOnly(TRUE)
      ->setTargetEntityTypeId($entity_type->id())
      ->setDisplayConfigurable('form', FALSE)
      ->setDisplayConfigurable('view', FALSE);
  }

  return $fields;
}

/**
 * Implements hook_entity_type_alter().
 *
 * @param array $entity_types
 */
function vactory_jsonapi_entity_type_alter(array &$entity_types) {
  $entity_types['comment']->addConstraint('jsonapi_recaptcha');
}
